import fs from 'fs';
import path from 'path';
import readline from 'readline';

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((r) => rl.question(q, r));

async function main() {
  console.log('=== Ollama Hub & Control Center - Environment Setup ===\n');

  const envPath = path.join(process.cwd(), '.env');
  let existing = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, 'utf8');
    for (const line of content.split('\n')) {
      const [k, ...v] = line.split('=');
      if (k) existing[k.trim()] = v.join('=').trim();
    }
    console.log('Existing .env file found. You can change values below.');
  }

  console.log('Configure your Ollama instance URL:');
  const defaultOllama = existing.OLLAMA_URL || 'http://localhost:11434';
  const ollamaUrl = (await ask(`Ollama URL [${defaultOllama}]: `)) || defaultOllama;

  console.log('\nConfigure Google Gemini API key (optional - for Sandbox fallback):');
  const defaultKey = existing.GEMINI_API_KEY || '';
  const masked = defaultKey ? defaultKey.slice(0, 4) + '****' + defaultKey.slice(-4) : '';
  const keyInput = await ask(`GEMINI_API_KEY [${masked || 'empty'}]: `);
  const geminiKey = keyInput || defaultKey;

  const envContent = [
    `OLLAMA_URL=${ollamaUrl}`,
    geminiKey ? `GEMINI_API_KEY=${geminiKey}` : '# GEMINI_API_KEY=your-key-here',
    '',
    `# Generated by setup-env on ${new Date().toISOString()}`,
  ].join('\n');

  fs.writeFileSync(envPath, envContent);
  console.log(`\n[OK] .env file written to ${envPath}`);

  rl.close();
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
